name: complex
on: [push]
env:
 ARTIFACT_NAAME: D360Artifact
jobs:
 ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      use: actions/checkout@v2
    - name: Upload the artifact
      use: actions/upload-artifact@v2
      with:
       name: ${{ env.ARTIFACT_NAME }}
       path: 
